services:
  db:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_db
    ports:
      - "5432:5432"
    healthcheck:   # Sağlık kontrolü ekleyelim
      test: ["CMD-SHELL", "pg_isready -U user -d task_db"]
      interval: 5s
      retries: 5
      timeout: 3s

  api:
    build: .
    container_name: fastapi_container
    depends_on:
      db:
        condition: service_healthy   # DB sağlıklı olmadan başlamaz
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db/task_db