services:
  db:
    image: postgres:15
    container_name: gpu_metrics_db
    restart: always
    environment:
      POSTGRES_DB: gpu_metrics
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: gpu_metrics_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:secret@db:5432/gpu_metrics
    ports:
      - "8000:8000"

  grafana:
    image: grafana/grafana
    container_name: gpu_metrics_grafana
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  postgres_data:
  grafana_data:
